name: CI

on: [push, pull_request]

jobs:
  lint-builder:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
        working-directory: ./tools
      - run: yarn run lint
        working-directory: ./tools

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
        working-directory: ./tools
      - run: yarn run build
        working-directory: ./tools

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-18.04
    env:
      IMAGE_PREFIX: docker.pkg.github.com/mofucoder/mofujudge-environment/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install --frozen-lockfile
        working-directory: ./tools

      - id: parse-tag-refs
        run: yarn run parseTagRefs
        working-directory: ./tools

      - name: Build ${{ steps.parse-tag-refs.outputs.name }}
        run: yarn run build $ENV_NAME
        working-directory: ./tools
        env:
          ENV_NAME: ${{ steps.parse-tag-refs.outputs.name }}

      - name: Generate an environment definition file for ${{ steps.parse-tag-refs.outputs.name }}
        run: yarn run generateEnvDefinition $ENV_NAME $ENV_VERSION
        working-directory: ./tools
        env:
          ENV_NAME: ${{ steps.parse-tag-refs.outputs.name }}
          ENV_VERSION: ${{ steps.parse-tag-refs.outputs.version }}

      - name: Login to GitHub Packages Docker Registry
        run: echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin docker.pkg.github.com
        env:
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Packages
        run: yarn run push $ENV_NAME $ENV_VERSION
        working-directory: ./tools
        env:
          ENV_NAME: ${{ steps.parse-tag-refs.outputs.name }}
          ENV_VERSION: ${{ steps.parse-tag-refs.outputs.version }}

      - name: Logout from GitHub Packages Docker Registry
        run: docker logout docker.pkg.github.com

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.parse-tag-refs.outputs.tag }}
          release_name: ${{ steps.parse-tag-refs.outputs.tag }}

      - name: Upload environment definition file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tools/dist/environment.json
          asset_name: ${{ steps.parse-tag-refs.outputs.tag }}.json
          asset_content_type: application/json
